In [2]:
import numpy as np
import pandas as pd
import sklearn

In [4]:
dataset=pd.read_csv('movie_review.csv')

In [5]:
dataset

fold_id cv_tag  html_id  sent_id  \
0            0  cv000    29590        0   
1            0  cv000    29590        1   
2            0  cv000    29590        2   
3            0  cv000    29590        3   
4            0  cv000    29590        4   
5            0  cv000    29590        5   
6            0  cv000    29590        6   
7            0  cv000    29590        7   
8            0  cv000    29590        8   
9            0  cv000    29590        9   
10           0  cv000    29590       10   
11           0  cv000    29590       11   
12           0  cv000    29590       12   
13           0  cv000    29590       13   
14           0  cv000    29590       14   
15           0  cv000    29590       15   
16           0  cv000    29590       16   
17           0  cv000    29590       17   
18           0  cv000    29590       18   
19           0  cv000    29590       19   
20           0  cv000    29590       20   
21           0  cv000    29590       21   
22           0  cv000    29590       22   
23           0  cv000    29590       23   
24           0  cv000    29590       24   
25           0  cv001    18431        0   
26           0  cv001    18431        1   
27           0  cv001    18431        2   
28           0  cv001    18431        3   
29           0  cv001    18431        4   
...        ...    ...      ...      ...   
64690        9  cv998    15691       20   
64691        9  cv998    15691       21   
64692        9  cv998    15691       22   
64693        9  cv998    15691       23   
64694        9  cv998    15691       24   
64695        9  cv999    14636        0   
64696        9  cv999    14636        1   
64697        9  cv999    14636        2   
64698        9  cv999    14636        3   
64699        9  cv999    14636        4   
64700        9  cv999    14636        5   
64701        9  cv999    14636        6   
64702        9  cv999    14636        7   
64703        9  cv999    14636        8   
64704        9  cv999    14636        9   
64705        9  cv999    14636       10   
64706        9  cv999    14636       11   
64707        9  cv999    14636       12   
64708        9  cv999    14636       13   
64709        9  cv999    14636       14   
64710        9  cv999    14636       15   
64711        9  cv999    14636       16   
64712        9  cv999    14636       17   
64713        9  cv999    14636       18   
64714        9  cv999    14636       19   
64715        9  cv999    14636       20   
64716        9  cv999    14636       21   
64717        9  cv999    14636       22   
64718        9  cv999    14636       23   
64719        9  cv999    14636       24   

                                                    text     tag  
0      films adapted from comic books have had plenty...    good  
1      for starters , it was created by alan moore ( ...     pos  
2      to say moore and campbell thoroughly researche...     pos  
3      the book ( or " graphic novel , " if you will ...     pos  
4      in other words , don't dismiss this film becau...     pos  
5      if you can get past the whole comic book thing...     pos  
6      getting the hughes brothers to direct this see...     pos  
7      the ghetto in question is , of course , whitec...     pos  
8      it's a filthy , sooty place where the whores (...     pos  
9      when the first stiff turns up , copper peter g...  better  
10     abberline , a widower , has prophetic dreams h...     pos  
11     upon arriving in whitechapel , he befriends an...     pos  
12     i don't think anyone needs to be briefed on ja...     pos  
13     in the comic , they don't bother cloaking the ...     pos  
14     it's funny to watch the locals blindly point t...     pos  
15     and from hell's ending had me whistling the st...     pos  
16     don't worry - it'll all make sense when you se...     pos  
17     now onto from hell's appearance : it's certain...    well  
18     the print i saw wasn't completely finished ( b...     pos  


In [6]:
dataset.info

<bound method DataFrame.info of        fold_id cv_tag  html_id  sent_id  \
0            0  cv000    29590        0   
1            0  cv000    29590        1   
2            0  cv000    29590        2   
3            0  cv000    29590        3   
4            0  cv000    29590        4   
5            0  cv000    29590        5   
6            0  cv000    29590        6   
7            0  cv000    29590        7   
8            0  cv000    29590        8   
9            0  cv000    29590        9   
10           0  cv000    29590       10   
11           0  cv000    29590       11   
12           0  cv000    29590       12   
13           0  cv000    29590       13   
14           0  cv000    29590       14   
15           0  cv000    29590       15   
16           0  cv000    29590       16   
17           0  cv000    29590       17   
18           0  cv000    29590       18   
19           0  cv000    29590       19   
20           0  cv000    29590       20   
21           0  cv000 

In [7]:
dataset1=dataset.drop(columns=['fold_id','cv_tag',"html_id",'sent_id'])

In [8]:
dataset1

text     tag
0      films adapted from comic books have had plenty...    good
1      for starters , it was created by alan moore ( ...     pos
2      to say moore and campbell thoroughly researche...     pos
3      the book ( or " graphic novel , " if you will ...     pos
4      in other words , don't dismiss this film becau...     pos
5      if you can get past the whole comic book thing...     pos
6      getting the hughes brothers to direct this see...     pos
7      the ghetto in question is , of course , whitec...     pos
8      it's a filthy , sooty place where the whores (...     pos
9      when the first stiff turns up , copper peter g...  better
10     abberline , a widower , has prophetic dreams h...     pos
11     upon arriving in whitechapel , he befriends an...     pos
12     i don't think anyone needs to be briefed on ja...     pos
13     in the comic , they don't bother cloaking the ...     pos
14     it's funny to watch the locals blindly point t...     pos
15     and from hell's ending had me whistling the st...     pos
16     don't worry - it'll all make sense when you se...     pos
17     now onto from hell's appearance : it's certain...    well
18     the print i saw wasn't completely finished ( b...     pos
19     oscar winner martin childs' ( shakespeare in l...     pos
20     even the acting in from hell is solid , with t...     pos
21     ians holm ( joe gould's secret ) and richardso...     pos
22     i cringed the first time she opened her mouth ...     pos
23                    the film , however , is all good .     pos
24     2 : 00 - r for strong violence/gore , sexualit...    well
25     every now and then a movie comes along from a ...     pos
26     mtv films' _election , a high school comedy st...     pos
27     did anybody know this film existed a week befo...     pos
28                      the plot is deceptively simple .     pos
29     george washington carver high school is having...     pos
...                                                  ...     ...
64690  and sheryl lee ( faring much better as laura p...     neg
64691  there is not an ounce of intelligence , or exc...     neg
64692  he has said that he turned down directing , " ...     neg
64693  and yet , when asked about a " vampires " sequ...     neg
64694  i think that's a definite sign that carpenter ...     neg
64695  two party guys bob their heads to haddaway's d...     neg
64696  while getting themselves into trouble in night...     neg
64697  it's barely enough to sustain a three-minute _...     neg
64698              emphasis on the word " presumably . "     neg
64699  _a_night_at_the_roxbury_ takes an already-thin...     neg
64700  the first five minutes or so of _roxbury_ play...     neg
64701                            with " what is love ? "     neg
64702  blaring on the soundtrack , the brotherly duo ...     neg
64703  there is one crucial difference , however--the...     neg
64704  that little fact has been used as justificatio...     neg
64705  the doors opened by director john fortenberry ...     neg
64706  there is no story per se , only a loosely stru...     neg
64707  the brothers literally run into ( or , rather ...     neg
64708  there , they meet a hotshot club owner ( chazz...     neg
64709  meanwhile , the bros' overbearing father ( dan...     neg
64710  when doug refuses and the dimwitted steve obey...     neg
64711  the narrative messiness of _roxbury_ would hav...     neg
64712  the assembled press audience mostly sat stonil...     neg
64713  alas , the joke--a rather lazy takeoff on _jer...     neg
64714  granted , a lot of people _have_ seen _jerry_m...     neg
64715  that lack of inspiration can be traced back to...     neg
64716  like too many of the skits on the current inca...     neg
64717  after watching one of the " roxbury " skits on...     neg
64718   bump unsuspecting women , and . . . that's all .     neg
64719  after watching _a_night_at_the_roxbury_ , you'...     neg

[64720 rows x 2 colum

In [9]:
list=[]

In [10]:
dataset1.text

0        films adapted from comic books have had plenty...
1        for starters , it was created by alan moore ( ...
2        to say moore and campbell thoroughly researche...
3        the book ( or " graphic novel , " if you will ...
4        in other words , don't dismiss this film becau...
5        if you can get past the whole comic book thing...
6        getting the hughes brothers to direct this see...
7        the ghetto in question is , of course , whitec...
8        it's a filthy , sooty place where the whores (...
9        when the first stiff turns up , copper peter g...
10       abberline , a widower , has prophetic dreams h...
11       upon arriving in whitechapel , he befriends an...
12       i don't think anyone needs to be briefed on ja...
13       in the comic , they don't bother cloaking the ...
14       it's funny to watch the locals blindly point t...
15       and from hell's ending had me whistling the st...
16       don't worry - it'll all make sense when you se.

In [11]:
dataset1.text[64690]


'and sheryl lee ( faring much better as laura palmer in " twin peaks " ) , like all of the female characters , plays an offensive stereotypical whore .'

In [12]:
np_matrix=dataset1.as_matrix()# to convert data in string into numpy array form

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [13]:
np_matrix

array([["films adapted from comic books have had plenty of success , whether they're about superheroes ( batman , superman , spawn ) , or geared toward kids ( casper ) or the arthouse crowd ( ghost world ) , but there's never really been a comic book like from hell before .",
        'good'],
       ["for starters , it was created by alan moore ( and eddie campbell ) , who brought the medium to a whole new level in the mid '80s with a 12-part series called the watchmen .",
        'pos'],
       ['to say moore and campbell thoroughly researched the subject of jack the ripper would be like saying michael jackson is starting to look a little odd .',
        'pos'],
       ...,
       ['after watching one of the " roxbury " skits on snl , this is what you come away with from the characters : they bob their heads to " what is love ? " ,',
        'neg'],
       ["bump unsuspecting women , and . . . that's all .", 'neg'],
       ["after watching _a_night_at_the_roxbury_ , you'll be left wit

In [14]:
dataset.tag.value_counts()

pos       32931
neg       31783
better        2
good          2
well          2
Name: tag, dtype: int64

In [15]:
dataset.text[3]

'the book ( or " graphic novel , " if you will ) is over 500 pages long and includes nearly 30 more that consist of nothing but footnotes .'

In [16]:
len(dataset)*.7

45304.0

In [17]:
train_size = int(len(dataset)*.7)
train_texts = dataset['text'][:train_size]
train_tags = dataset['tag'][:train_size]

test_texts = dataset['text'][train_size:]
test_tags = dataset['tag'][train_size:]

In [18]:
train_texts

0        films adapted from comic books have had plenty...
1        for starters , it was created by alan moore ( ...
2        to say moore and campbell thoroughly researche...
3        the book ( or " graphic novel , " if you will ...
4        in other words , don't dismiss this film becau...
5        if you can get past the whole comic book thing...
6        getting the hughes brothers to direct this see...
7        the ghetto in question is , of course , whitec...
8        it's a filthy , sooty place where the whores (...
9        when the first stiff turns up , copper peter g...
10       abberline , a widower , has prophetic dreams h...
11       upon arriving in whitechapel , he befriends an...
12       i don't think anyone needs to be briefed on ja...
13       in the comic , they don't bother cloaking the ...
14       it's funny to watch the locals blindly point t...
15       and from hell's ending had me whistling the st...
16       don't worry - it'll all make sense when you se.

In [19]:
test_tags

45304    neg
45305    neg
45306    neg
45307    neg
45308    neg
45309    neg
45310    neg
45311    neg
45312    neg
45313    neg
45314    neg
45315    neg
45316    neg
45317    neg
45318    neg
45319    neg
45320    neg
45321    neg
45322    neg
45323    neg
45324    neg
45325    neg
45326    neg
45327    neg
45328    neg
45329    neg
45330    neg
45331    neg
45332    neg
45333    neg
        ... 
64690    neg
64691    neg
64692    neg
64693    neg
64694    neg
64695    neg
64696    neg
64697    neg
64698    neg
64699    neg
64700    neg
64701    neg
64702    neg
64703    neg
64704    neg
64705    neg
64706    neg
64707    neg
64708    neg
64709    neg
64710    neg
64711    neg
64712    neg
64713    neg
64714    neg
64715    neg
64716    neg
64717    neg
64718    neg
64719    neg
Name: tag, Length: 19416, dtype: object

In [20]:
test_texts

45304    whilst richard gere still proves that has what...
45305                          martin vailwhere are you ?
45306    not so long ago , men by the names of peckinpa...
45307                                      real westerns .
45308    these were some of the best films of the twent...
45309                                those days are gone .
45310    now we have crap like wild wild west to pass f...
45311    and that record is not improved with the unbea...
45312    outlaws is yet another re-telling of the jesse...
45313    delayed since the spring , this version stars ...
45314    alas , any sense of his character has been lef...
45315    the spin this time around : fresh from serving...
45316    but trouble is brewing in their small town of ...
45317    the jameses and the youngers then join forces ...
45318    along the way , the boys squabble over who's t...
45319    they rob numerous banks with identical interio...
45320    the witty banter they share could be plastered.

In [21]:
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.preprocessing.text import Tokenizer

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [22]:
max_words = 5000
tokenize = Tokenizer(num_words=max_words, char_level=False)
tokenize.fit_on_texts(train_texts) # only fit on train

x_train = tokenize.texts_to_matrix(train_texts)
x_test = tokenize.texts_to_matrix(test_texts)

In [23]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [24]:
x_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [25]:
encoder = LabelEncoder()
encoder.fit(train_tags)
y_train = encoder.transform(train_tags)
y_test = encoder.transform(test_tags)

In [26]:
y_test

array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [27]:
encoder.classes_

array(['better', 'good', 'neg', 'pos', 'well'], dtype=object)

In [28]:
import numpy as np

In [29]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4], dtype=int64)

In [30]:
from keras import utils
y_train_new = utils.to_categorical(y_train)
y_test_new =  utils.to_categorical(y_test)


In [31]:
y_test_new

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [32]:
y_train_new

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [33]:
model = Sequential()
model.add(Dense(560, input_shape=(max_words,),activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


In [34]:
model.add(Dense(5,activation='softmax'))

In [35]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [57]:
history = model.fit(x_train, y_train_new,batch_size=32,epochs=1,verbose=1,validation_split=0.1)

Train on 40773 samples, validate on 4531 samples
Epoch 1/1
40773/40773 [==============================] - 69s 2ms/step - loss: 0.0735 - acc: 0.9783 - val_loss: 2.8488 - val_acc: 0.2280


In [37]:
##score = model.evaluate(x_test, y_test_new)
##print('Test accuracy:', score[5])

In [58]:
new=tokenize.texts_to_matrix(['movie-is-boring'])

In [59]:
k=model.predict_classes(new)
k

array([2], dtype=int64)

In [60]:
encoder.classes_[2]

'neg'

In [63]:
model.save('ku.h5')